export const START_TIMER = 'START_TIMER';
export const STOP_TIMER = 'STOP_TIMER';
export const RESET_TIMER = 'RESET_TIMER';
export const TICK = 'TICK';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const PAUSE_UPDATE_LOCATION = 'PAUSE_UPDATE_LOCATION';
export const RESET_LOCATION = 'RESET_LOCATION';
export const SHOW_SLIDING_PANEL = 'SHOW_SLIDING_PANEL';
export const HIDE_SLIDING_PANEL = 'HIDE_SLIDING_PANEL';
export const CHOOSE_FEEL_SCALE = 'CHOOSE_FEEL_SCALE';
export const CHOOSE_POOP_SHAPE = 'CHOOSE_POOP_SHAPE';
export const CHOOSE_POOP_COLOR = 'CHOOSE_POOP_COLOR';
export const CHOOSE_PEE = 'CHOOSE_PEE';
export const CHOOSE_POOP = 'CHOOSE_POOP';
export const RESET_RECORD = 'RESET_RECORD';
/*
 *  History types
 */
export const UPDATE_HISTORY_DATA = 'UPDATE_HISTORY_DATA';

export const QUERY_RECORDS_REQUEST = 'QUERY_RECORDS_REQUEST';
export const QUERY_RECORDS_SUCCESS = 'QUERY_RECORDS_SUCCESS';
export const QUERY_RECORDS_FAILURE = 'QUERY_RECORDS_FAILURE';
export const DELETE_RECORD_REQUEST = 'DELETE_RECORD_REQUEST';
export const DELETE_RECORD_SUCCESS = 'DELETE_RECORD_SUCCESS';
export const DELETE_RECORD_FAILURE = 'DELETE_RECORD_FAILURE';

export const INSERT_RECORD_REQUEST = 'INSERT_REOCRD_REQUEST';
export const INSERT_RECORD_SUCCESS = 'INSERT_RECORD_SUCCESS';
export const INSERT_RECORD_FAILURE = 'INSERT_RECORD_FAILURE';

export const UPDATE_DOG_PROFILE = 'UPDATE_DOG_PROFILE';
